<template>
  <main class="expedientes"><header><div><h1>Disciplina laboral</h1><p>Expedientes documentales; la anulación conserva la trazabilidad y no afecta nómina.</p></div><button class="primary" @click="abrirNuevo">+ Nueva incidencia</button></header>
    <section class="filters"><label>Finca<select v-model="fincaId" @change="cargar"><option value="">Seleccione</option><option v-for="f in fincas" :key="f.id" :value="f.id">{{ f.code }} - {{ f.name }}</option></select></label><label>Desde<input v-model="desde" type="date" @change="cargar"></label><label>Hasta<input v-model="hasta" type="date" @change="cargar"></label><label class="check"><input v-model="incluirAnulados" type="checkbox" @change="cargar"> Ver anulados</label></section>
    <p v-if="cargando">Cargando expedientes…</p><p v-else-if="!fincaId" class="empty">Seleccione una finca para consultar.</p>
    <table v-else><thead><tr><th>Fecha</th><th>Trabajador</th><th>Incidencia</th><th>Estado</th><th>Aprobador</th><th>Acciones</th></tr></thead><tbody><tr v-for="e in expedientes" :key="e.id"><td>{{ fecha(e.fecha) }}</td><td>{{ e.trabajadorNombre }}</td><td>{{ etiquetaTipo(e.tipo) }}</td><td><span class="tag" :class="e.estado.toLowerCase()">{{ etiquetaEstado(e.estado) }}</span></td><td>{{ e.aprobadorNombre || '—' }}</td><td class="actions"><button @click="verPdf(e)">PDF</button><button v-if="e.estado==='BORRADOR'" @click="notificar(e)">Notificar</button><button v-if="e.estado==='NOTIFICADA'" @click="resolver(e)">Resolver</button><button v-if="e.estado==='BORRADOR'||e.estado==='NOTIFICADA'" class="danger" @click="anular(e)">Anular</button></td></tr><tr v-if="!expedientes.length"><td colspan="6" class="empty">No hay expedientes para los filtros seleccionados.</td></tr></tbody></table>
    <div v-if="mostrar" class="overlay"><form class="modal" @submit.prevent="guardar"><header><h2>Nueva incidencia</h2><button type="button" @click="mostrar=false">×</button></header><label>Trabajador<select v-model="form.trabajadorId" required><option value="">Seleccione</option><option v-for="t in trabajadores" :key="t.id" :value="t.id">{{ t.nombre }}</option></select></label><label>Fecha<input v-model="form.fecha" type="date" required></label><label>Tipo<select v-model="form.tipo" required><option value="TARDANZA">Tardanza</option><option value="AUSENCIA">Ausencia</option><option value="INCUMPLIMIENTO">Incumplimiento</option><option value="OTRA">Otra</option></select></label><label>Aprobador<select v-model="form.aprobadorId"><option value="">Sin asignar</option><option v-for="t in trabajadores" :key="t.id" :value="t.id">{{ t.nombre }}</option></select></label><label>Descripción<textarea v-model.trim="form.descripcion" required maxlength="3000"></textarea></label><label>Evidencia / referencia<textarea v-model.trim="form.evidencia" maxlength="3000"></textarea></label><label>Observaciones<textarea v-model.trim="form.observaciones" maxlength="3000"></textarea></label><footer><button type="button" @click="mostrar=false">Cancelar</button><button class="primary" :disabled="guardando">{{ guardando ? 'Guardando…' : 'Guardar borrador' }}</button></footer></form></div>
  </main>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import FincaService from '@/services/FincaService'
import TrabajadorService from '@/services/TrabajadorService'
import ExpedienteService, { type ExpedienteDisciplinario, type CrearExpediente } from '@/services/ExpedienteDisciplinarioService'
import { notify } from '@/composables/useNotification'
const fincas=ref<Array<{id:string;code:string;name:string}>>([]), trabajadores=ref<Array<{id:string;nombre:string;fincaId:string;activo?:boolean}>>([]), expedientes=ref<ExpedienteDisciplinario[]>([]), fincaId=ref(''), desde=ref(''), hasta=ref(''), incluirAnulados=ref(false), cargando=ref(false), guardando=ref(false), mostrar=ref(false)
const hoy=new Date().toISOString().slice(0,10); const form=reactive<CrearExpediente>({fincaId:'',trabajadorId:'',tipo:'TARDANZA',fecha:hoy,descripcion:'',evidencia:'',observaciones:''})
const fecha=(v:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString('es-CU'):'—'; const etiquetaTipo=(v:string)=>({TARDANZA:'Tardanza',AUSENCIA:'Ausencia',INCUMPLIMIENTO:'Incumplimiento',OTRA:'Otra'}[v]||v); const etiquetaEstado=(v:string)=>({BORRADOR:'Borrador',NOTIFICADA:'Notificada',RESUELTA:'Resuelta',ANULADA:'Anulada'}[v]||v)
async function cargar(){if(!fincaId.value)return; cargando.value=true;try{const r=await ExpedienteService.listar({fincaId:fincaId.value,desde:desde.value||undefined,hasta:hasta.value||undefined,incluirAnulados:incluirAnulados.value});expedientes.value=r.data||[];const t=await TrabajadorService.buscarTrabajadores({size:999});trabajadores.value=(t.data.data||[]).filter((x:any)=>x.fincaId===fincaId.value&&x.activo!==false)}catch(e){console.error(e);notify.error('Disciplina laboral','No se pudieron cargar los expedientes.')}finally{cargando.value=false}}
function abrirNuevo(){if(!fincaId.value){notify.warning('Seleccione una finca','Debe definir la finca antes de crear una incidencia.');return} form.fincaId=fincaId.value;form.trabajadorId='';form.aprobadorId='';form.tipo='TARDANZA';form.fecha=hoy;form.descripcion='';form.evidencia='';form.observaciones='';mostrar.value=true}
async function guardar(){if(!form.descripcion||!form.trabajadorId)return;guardando.value=true;try{await ExpedienteService.crear({...form,aprobadorId:form.aprobadorId||undefined,evidencia:form.evidencia||undefined,observaciones:form.observaciones||undefined});mostrar.value=false;await cargar();notify.success('Borrador creado','La incidencia no produce efectos salariales ni de nómina.')}catch(e){console.error(e);notify.error('No se pudo guardar','Revise los datos de la incidencia.')}finally{guardando.value=false}}
async function notificar(e:ExpedienteDisciplinario){if(!confirm('¿Marcar este expediente como notificado?'))return;try{await ExpedienteService.notificar(e.id);await cargar();notify.success('Expediente notificado','El expediente queda listo para resolución.')}catch(x){console.error(x);notify.error('No se pudo notificar','La operación fue rechazada.')}}
async function resolver(e:ExpedienteDisciplinario){const medida=prompt('Medida aplicada:');if(!medida?.trim())return;const resolucion=prompt('Resolución:');if(!resolucion?.trim())return;try{await ExpedienteService.resolver(e.id,{medida:medida.trim(),resolucion:resolucion.trim(),aprobadorId:e.aprobadorId});await cargar();notify.success('Expediente resuelto','La resolución quedó registrada.')}catch(x){console.error(x);notify.error('No se pudo resolver','La operación fue rechazada.')}}
async function anular(e:ExpedienteDisciplinario){const motivo=prompt('Motivo de anulación:');if(!motivo?.trim())return;try{await ExpedienteService.anular(e.id,motivo.trim());await cargar();notify.success('Expediente anulado','El registro se conserva para auditoría.')}catch(x){console.error(x);notify.error('No se pudo anular','La operación fue rechazada.')}}
async function verPdf(e:ExpedienteDisciplinario){try{const r=await ExpedienteService.pdf(e.id);const url=URL.createObjectURL(r.data);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(x){console.error(x);notify.error('PDF','No se pudo generar el documento.')}}
onMounted(async()=>{try{const r=await FincaService.buscarFincas({size:999});fincas.value=r.data.data||[]}catch(e){console.error(e);notify.error('Fincas','No se pudieron cargar las fincas.')}})
</script>
<style scoped>.expedientes{padding:24px;max-width:1300px;margin:auto}header,.filters,footer{display:flex;align-items:center;gap:14px;justify-content:space-between}h1{margin:0}.filters{margin:22px 0;justify-content:flex-start;flex-wrap:wrap}label{display:grid;gap:5px;font-weight:600}.check{display:flex;align-items:center;margin-top:18px}input,select,textarea,button{font:inherit;padding:8px;border:1px solid #cbd5e1;border-radius:6px}textarea{min-height:82px;resize:vertical}.primary{background:#176b46;color:#fff;border-color:#176b46}.danger{color:#b42318}.actions{display:flex;gap:6px;flex-wrap:wrap}table{width:100%;border-collapse:collapse;background:#fff}th,td{padding:10px;border-bottom:1px solid #e2e8f0;text-align:left}.tag{padding:3px 8px;border-radius:99px;font-size:.85em}.borrador{background:#e0f2fe}.notificada{background:#fef3c7}.resuelta{background:#dcfce7}.anulada{background:#fee2e2}.empty{text-align:center;color:#64748b;padding:22px}.overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:20}.modal{width:min(650px,94vw);max-height:92vh;overflow:auto;background:white;padding:20px;border-radius:10px;display:grid;gap:12px}.modal header button{border:0;background:none;font-size:24px}@media(max-width:700px){.expedientes{padding:14px}table{font-size:.85em}.filters{align-items:flex-end}}</style>
